# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


setup(
    install_requires=[
        'aiodns', 'aiogram==2.25.1', 'aiohttp[speedups]', 'apscheduler',
        'beautifulsoup4', 'boto3', 'brotlipy', 'colorama', 'ffmpeg-python',
        'flask-sqlalchemy', 'flask-wtf', 'furhat-remote-api',
        'google-search-results', 'graphviz', 'install-requires', 'lxml',
        'matplotlib', 'mpmath', 'natsort', 'networkx[default]', 'nltk', 'numpy',
        'ollama', 'openai', 'pandas', 'pydantic', 'pydantic-settings', 'pypng',
        'pyqrcode', 'python-telegram-bot', 'pytz', 'quart', 'quart-flask-patch',
        'requests', 'sympy', 'tabulate', 'ujson', 'urllib3', 'uvicorn',
        'uvloop', 'validators', 'web3', 'youtube-dl', 'yt-dlp',
        'zc.zlibstorage', 'zodb'
    ]
)
