"""
Default configuration for ia.cecil
PT: Copiar este pacote para instance/bots/bot.py e editar lá  
EN: Copy this package to instance/bots/bot.py and edit it there  

ia.cecil

Copyleft 2012-2022 Iuri Guilherme <https://iuri.neocities.org/>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

!!!!!!!!!!!!!!! ATENÇÃO !!!!!!!!!!!!!!!  
Vós que vierdes editar este arquivo, perdei toda a esperança! O lugar 
apropriado para configurar o aplicativo é criando um diretório instance/bots 
e colocando um arquivo para cada bot novo.  
Este é o arquivo de configuração padrão que é carregado quando nenhum arquivo 
de configuração é encontrado. Ou seja, este arquivo é testado e criado para 
funcionar sempre que tiver problema nos arquivos de configurações do site onde 
os bots estão rodando. E portanto, se este arquivo for alterado e tiver erros 
de sintaxe ou importação, vai dar tudo errado!  
Use este arquivo como referência ou copie ele para instance/bots/meubot.py e 
edite lá!  
!!!!!!!!!!!!!!! ATENÇÃO !!!!!!!!!!!!!!!  

WARNING: Do not edit this file. Copy it over to instance/bots/mybot.py and 
edit it there, for each bot. This is the default configuration file that is 
loaded whenever configuration files are not found or have problems. The full 
explanation to such a request lies in the above portuguese notice, please 
translate it to your local language, thanks.  
"""

from pydantic import BaseSettings

class BotConfig(BaseSettings):
    """Default bot configuration"""
    ## All plugins: 'default', 'admin', 'archive', 'cryptoforex',
    ## 'donate', 'echo', 'feedback', 'garimpo', 'greatful',
    ## 'hashes', 'mate_matica', 'natural', 'portaria',
    ## 'qr', 'storify', 'totalvoice', 'tropixel', 'tts',
    ## 'welcome', 'ytdl'
    ## FIXME: Some plugins currently will not work if loaded after others,
    ## have to find out which is the correct order
    plugins: dict = {
        'enable': ['default'],
        'disable': ['echo'],
    }
    info: dict = {
        'website': "http://iuri.xyz/iacecil",
        'repository': "https://github.com/iuriguilherme/iacecil",
    }
    
    ## Plugin donate - doações
    donate: dict = {
        'BCH': '1HFG6ici2SGU61hPFFtUsPVGMkdiimBPDL',
        'BTC': '1MQJSCb6VopUeYrrsQaFVwmyFzs1hffcD2',
        'DOGE': 'DAeuBKyt6gSnD5rT5eBtjvXqdGvFWVkh9D',
        'ETH': '0x083652085dc46ab2d6146fbb329db0cde48eea81',
        'FLO': 'F87gjmfeF9nWh1suB5X2TZQNN6FaQyWzxp',
        'LTC': 'LY8w2WBRogttTJbLfusrJogi2tp6rKrPc3',
        'PIVX': 'D9bUN6xhDTRUZYCT54yLw6L2F1QaMJ3oTC',
        'TRX': 'TTCooALnSqmFcK3q56WMnGmbYhaXR6Zh5e',
    } # donate
    
    ## Plugin Tropixel
    tropixel: dict = {
        'site': "https://rede.tropixel.org/",
        'boteco': "https://meet.jit.si/tropixelbr",
    }
    ## Plugin personalidade
    ## List of working personalidades: 'iacecil', 'cryptoforex', 'default', 
    ## 'matebot', 'metarec', 'pave', 'pacume', 'pasoca'
    personalidade: str = 'default'
    
    ## Plugin cryptoforex
    coinmarketcap: dict = {
        'token': '12345678-90ab-cdef-1234-567890abcdef',
    } # coinmarketcap
    
    ## Plugin TextoTecidoPalavra
    tecido: dict = {
        'host': '127.0.0.1',
        'port': 3000,
    } # tecido
    
    ## Plugin web3_wrapper
    web3: dict = {
        'binance': {
            'bsc_mainnet': 'https://bsc-dataseed1.binance.org:443',
            'bsc_testnet': 'https://data-seed-prebsc-1-s1.binance.org:8545',
        }, # binance
        'infura': {
            'eth_mainnet': 'https://mainnet.infura.io/v3/0123456789abcdef0123456789abcdef',
            'eth2_mainnet': 'https://0123456789abcdef0123456789abcdef:0123456789abcdef0123456789abcdef@eth2-beacon-mainnet.infura.io',
            'filecoin': 'https://0123456789abcdef0123456789abcdef:0123456789abcdef0123456789abcdef@filecoin.infura.io',
        }, # infura
    } # web3
    
    ## Plugin calendar
    jobs: list = []
    timezone: str = 'Etc/UTC'
    
    ## Plugin tc
    serpapi: dict = {
        'api_key': "123456789abcdef",
    }
    
    quart: dict = {}
    telegram: dict = {
        'token': None,
        'info': {
            'group': "https://t.me/joinchat/CwFUFkf-dKW34FPBjEJs9Q",
            'channel': "@matebotnews",
            'admin': "@desobedientecivil",
            'dev': "@desobedientecivil",
        },
        'webhook': {
            'host': 'https://iacecil.iuri.xyz/webhook/',
            'path': '/iacecil',
            'webapp': 'https://iacecil.iuri.xyz/webhook/iacecil/',
            'port': 8443,
        }, # webhook
        ## Plugin portaria
        'unwanted': [
            'HV Cursos',
            'MateBot (test)',
        ], # unwanted
        'users': {
            'alpha': [
                -1001233916997, # pub4 test
            ],
            'beta': [
                -1001233916997, # pub4 test
                -1001123697262, # MateBot News
            ],
            'gamma': [
                -1001286967165, # pub1 G
                -296878012, # pub2 C
                -1001207858341, # pub3 M
                -1001233916997, # pub4 test
                -481703172, # pub5 test
            ],
            'delta': [
            ],
            'epsilon': [
                777000, # services
                -1001286967165, # pub1 G
                -296878012, # pub2 C
                -1001207858341, # pub3 M
                -1001233916997, # pub4 test
                -481703172, # pub5 test
                -1001123697262, # MateBot News
                # @mate_obot
            ], # epsilon
            'tropixel': [
                -1001233916997, # pub4 test
            ], # tropixel
            'pegadinha': [
                -1001233916997, # pub4 test
            ], # pegadinha
            'garimpo': [
                -1001233916997, # pub4 test
            ],
            'special': {
                'services': 777000,
                'nouser': 1,
                'nogroup': -1,
                'debug': -1001233916997, # pub4 test
                'feedback': -1001233916997, # pub4 test
                'info': -1001233916997, # pub4 test
                'test': -1001233916997, # pub4 test
                'log_test': -1001233916997, # pub4 test
            }, # special
        }, # users
    } # telegram
    discord: dict = {
        'token': None,
    } # discord
    furhat: dict = {
        'bot': 'f1',
        'address': '127.0.0.1',
        'voice': 'Camila',
        'mask': 'adult',
        'character': 'Titan',
        'language': 'pt-BR',
        'led': {'green': 0, 'red': 150, 'blue': 30},
        'attend': {'x': 0, 'y': 0, 'z': 0},
        'voice_url': 'https://www.intriguing.com/mp/_sounds/hg/',
        'recognizer': {
            # https://cloud.google.com/speech/docs/getting-started
            'google': {
                "type": "service_account",
                "project_id": "acquired-sunup-165115",
                "private_key_id": "1234567890abcdef",
                "private_key": "privatekey",
                "client_email": "example@example.com",
                "client_id": "123456789",
                "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                "token_uri": "https://oauth2.googleapis.com/token",
                "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
                "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/example@example.com",
            }, # google
            ## https://azure.microsoft.com/en-us/services/cognitive-services/speech-to-text/
            'microsoft': {}, # microsoft
        }, # recognizer
        'synthesizer': {
            ## https://aws.amazon.com/pt/polly/
            'amazon': {
                'secret': '1234567890abcdef',
                'key': 'ABCDEF',
                'engine': 'neural',
            }, # amazon
            ## https://www.acapela-group.com/solutions/acapela-cloud/
            'acapela': {}, # acapela
        }, # synthesizer
        'extension': 'wav',
        'output_format': 'pcm',
    } # furhat
